### ISSUE TITLE
Request to transfer the linux crate to the Rust project

### ISSUE THREAD

**Issue by gnzlbg** [mahkoh/dotfiles#1]
Dear @mahkoh ,

I'm considering moving the FFI APIs to the linux kernel from the Rust `libc` crate to a separate crate (I currently maintain the libc crate), and I just noticed that the `linux` crate name is reserved on crates.io. 

Would you mind transferring this crate name to me? 

Best regards

**Comment by mahkoh** [comment]
I am currently working on porting https://github.com/lrs-lang/lib to rust. The port will contain a complete wrapping of the linux syscall api among other things. You will agree that this is a better use of the linux crate name.
